#!/bin/bash

# This script should be used to build or build and publish provider-cloudeos
# binaries to dist. To build only, run this script as "./publish_terraform b".
# To build and publish, run as "./publish_terraform" directly.
#
# Note, when build only provider-cloudeos version number will not change,
# when build and publish, script will increment version number to build
# and publish binaries with this new version number. New version number
# must be merged so people will be on same page.

# Read current version from version file
vfile="./cloudeos/version.go"
if [ -f "$vfile" ]; then
    version=$(cat $vfile | grep providerCloudEOSVersion | grep -oP [0-9]+.[0-9]+.[0-9]+)
else
   version="0.0.0"
fi
echo provider-cloudeos current version $version

# Increment the version if we are publishing
if [ $# -eq 0 ] || [ $1 != 'b' ]; then
    oldversion=$version
    IFS='.'
    read -ra ADDR <<< "$version"
    d=${ADDR[2]}
    IFS=$OLDIFS
    version="${ADDR[0]}.${ADDR[1]}.$((d+1))"
    echo provider-cloudeos version $oldversion to $version

    # Write the new version back to version file
    sed -i "s/$oldversion/$version/g" "$vfile"
fi

# The directory structure matches what tf expects for providers setup locally(in our case
# cloudeos). See https://www.terraform.io/docs/cloud/run/install-software.html#in-house-providers
# When terraform init is invoked, the cloudeos provider in terraform.d will be picked up
# and the remaining providers will be downloaded and setup in .terraform dir
pushd ./
mkdir -p terraform.d/plugins/registry.terraform.io/aristanetworks/cloudeos/$version
cd terraform.d/plugins/registry.terraform.io/aristanetworks/cloudeos/$version
mkdir darwin_amd64
mkdir linux_amd64
popd

# Build binaries and put into corresponding directories
echo Building provider-cloudeos binary terraform-provider-cloudeos_v$version
CGO_ENABLED=0 GOOS=linux go build -o terraform-provider-cloudeos_v$version
mv terraform-provider-cloudeos_v$version terraform.d/plugins/registry.terraform.io/aristanetworks/cloudeos/$version/linux_amd64

CGO_ENABLED=0 GOOS=darwin go build -o terraform-provider-cloudeos_v$version
mv terraform-provider-cloudeos_v$version terraform.d/plugins/registry.terraform.io/aristanetworks/cloudeos/$version/darwin_amd64

if [ $# -eq 0 ] || [ $1 != 'b' ]; then
    echo Publishing provider-cloudeos binary tarball terraform-cloudeos-plugin_v$version.tar.gz and terraform-cloudeos-plugin_latest.tar.gz
    # Create tarball and publish
    tar -czvf terraform-cloudeos-plugin_v$version.tar.gz terraform.d
    a4 scp terraform-cloudeos-plugin_v$version.tar.gz $1
    tar -czvf terraform-cloudeos-plugin_latest.tar.gz terraform.d
    a4 scp terraform-cloudeos-plugin_dev_latest_13.tar.gz $1

    echo Cleaning up
    # Cleaning up
    rm -r terraform.d
    rm terraform-cloudeos-plugin*

    echo Please git add/commit/push and merge your version file change!!!
fi
