// Copyright (c) 2020 Arista Networks, Inc.
// Use of this source code is governed by the Mozilla Public License Version 2.0
// that can be found in the LICENSE file.

// source: https://github.com/aristanetworks/cloudvision-apis/blob/trunk/arista/subscriptions/subscriptions.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: subscriptions/subscriptions.proto

package subscriptions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_UNSPECIFIED Operation = 0
	// INITIAL indicates the associated notification is that of the
	// current state and a fully-specified Resource is provided.
	Operation_INITIAL Operation = 10
	// INITIAL_SYNC_COMPLETE indicates all existing-state has been
	// streamed to the client. This status will be sent in an
	// otherwise-empty message and no subsequent INITIAL messages
	// should be expected.
	Operation_INITIAL_SYNC_COMPLETE Operation = 11
	// UPDATED indicates the associated notification carries
	// modification to the last-streamed state. This indicates
	// the contained Resource may be a partial diff, though, it
	// may contain a fully-specified Resource.
	Operation_UPDATED Operation = 20
	// DETLETED indicates the associated notification carries
	// a deletion. The Resource's key will always be set in this case,
	// but no other fields should be expected.
	Operation_DELETED Operation = 30
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0:  "UNSPECIFIED",
		10: "INITIAL",
		11: "INITIAL_SYNC_COMPLETE",
		20: "UPDATED",
		30: "DELETED",
	}
	Operation_value = map[string]int32{
		"UNSPECIFIED":           0,
		"INITIAL":               10,
		"INITIAL_SYNC_COMPLETE": 11,
		"UPDATED":               20,
		"DELETED":               30,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_subscriptions_subscriptions_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_subscriptions_subscriptions_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_subscriptions_subscriptions_proto_rawDescGZIP(), []int{0}
}

var File_subscriptions_subscriptions_proto protoreflect.FileDescriptor

var file_subscriptions_subscriptions_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x61, 0x72, 0x69, 0x73, 0x74, 0x61, 0x2e, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2a, 0x5e, 0x0a, 0x09, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x49, 0x54, 0x49,
	0x41, 0x4c, 0x10, 0x0a, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x5f,
	0x53, 0x59, 0x4e, 0x43, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x0b, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10, 0x14, 0x12, 0x0b, 0x0a, 0x07,
	0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x1e, 0x42, 0x3d, 0x5a, 0x3b, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x65, 0x6f, 0x73, 0x2d, 0x74, 0x65, 0x72, 0x72, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x2d,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x65, 0x6f,
	0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_subscriptions_subscriptions_proto_rawDescOnce sync.Once
	file_subscriptions_subscriptions_proto_rawDescData = file_subscriptions_subscriptions_proto_rawDesc
)

func file_subscriptions_subscriptions_proto_rawDescGZIP() []byte {
	file_subscriptions_subscriptions_proto_rawDescOnce.Do(func() {
		file_subscriptions_subscriptions_proto_rawDescData = protoimpl.X.CompressGZIP(file_subscriptions_subscriptions_proto_rawDescData)
	})
	return file_subscriptions_subscriptions_proto_rawDescData
}

var file_subscriptions_subscriptions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_subscriptions_subscriptions_proto_goTypes = []interface{}{
	(Operation)(0), // 0: arista.subscriptions.Operation
}
var file_subscriptions_subscriptions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subscriptions_subscriptions_proto_init() }
func file_subscriptions_subscriptions_proto_init() {
	if File_subscriptions_subscriptions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_subscriptions_subscriptions_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subscriptions_subscriptions_proto_goTypes,
		DependencyIndexes: file_subscriptions_subscriptions_proto_depIdxs,
		EnumInfos:         file_subscriptions_subscriptions_proto_enumTypes,
	}.Build()
	File_subscriptions_subscriptions_proto = out.File
	file_subscriptions_subscriptions_proto_rawDesc = nil
	file_subscriptions_subscriptions_proto_goTypes = nil
	file_subscriptions_subscriptions_proto_depIdxs = nil
}
