// Copyright (c) 2020 Arista Networks, Inc.
// Use of this source code is governed by the Mozilla Public License Version 2.0
// that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/terraform-providers/terraform-provider-cloudeos/cloudeos/internal/time/time.proto

package time

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TimeRange struct {
	StartTime            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimeRange) Reset()         { *m = TimeRange{} }
func (m *TimeRange) String() string { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()    {}
func (*TimeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_a24e7382f0d9ac4c, []int{0}
}

func (m *TimeRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRange.Unmarshal(m, b)
}
func (m *TimeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRange.Marshal(b, m, deterministic)
}
func (m *TimeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRange.Merge(m, src)
}
func (m *TimeRange) XXX_Size() int {
	return xxx_messageInfo_TimeRange.Size(m)
}
func (m *TimeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRange.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRange proto.InternalMessageInfo

func (m *TimeRange) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *TimeRange) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type RequestAtTime struct {
	// Types that are valid to be assigned to AtTime:
	//	*RequestAtTime_Range
	//	*RequestAtTime_Time
	AtTime               isRequestAtTime_AtTime `protobuf_oneof:"at_time"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RequestAtTime) Reset()         { *m = RequestAtTime{} }
func (m *RequestAtTime) String() string { return proto.CompactTextString(m) }
func (*RequestAtTime) ProtoMessage()    {}
func (*RequestAtTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_a24e7382f0d9ac4c, []int{1}
}

func (m *RequestAtTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAtTime.Unmarshal(m, b)
}
func (m *RequestAtTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAtTime.Marshal(b, m, deterministic)
}
func (m *RequestAtTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAtTime.Merge(m, src)
}
func (m *RequestAtTime) XXX_Size() int {
	return xxx_messageInfo_RequestAtTime.Size(m)
}
func (m *RequestAtTime) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAtTime.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAtTime proto.InternalMessageInfo

type isRequestAtTime_AtTime interface {
	isRequestAtTime_AtTime()
}

type RequestAtTime_Range struct {
	Range *TimeRange `protobuf:"bytes,1,opt,name=range,proto3,oneof"`
}

type RequestAtTime_Time struct {
	Time *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3,oneof"`
}

func (*RequestAtTime_Range) isRequestAtTime_AtTime() {}

func (*RequestAtTime_Time) isRequestAtTime_AtTime() {}

func (m *RequestAtTime) GetAtTime() isRequestAtTime_AtTime {
	if m != nil {
		return m.AtTime
	}
	return nil
}

func (m *RequestAtTime) GetRange() *TimeRange {
	if x, ok := m.GetAtTime().(*RequestAtTime_Range); ok {
		return x.Range
	}
	return nil
}

func (m *RequestAtTime) GetTime() *timestamp.Timestamp {
	if x, ok := m.GetAtTime().(*RequestAtTime_Time); ok {
		return x.Time
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RequestAtTime) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RequestAtTime_Range)(nil),
		(*RequestAtTime_Time)(nil),
	}
}

func init() {
	proto.RegisterType((*TimeRange)(nil), "time.TimeRange")
	proto.RegisterType((*RequestAtTime)(nil), "time.RequestAtTime")
}

func init() {
	proto.RegisterFile("arista/resources/protobuf/time/time.proto", fileDescriptor_a24e7382f0d9ac4c)
}

var fileDescriptor_a24e7382f0d9ac4c = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4c, 0x2c, 0xca, 0x2c,
	0x2e, 0x49, 0xd4, 0x2f, 0x4a, 0x2d, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0x2d, 0xd6, 0x2f, 0x28, 0xca,
	0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0xc9, 0xcc, 0x4d, 0x05, 0x13, 0x7a, 0x60, 0x21, 0x21,
	0x16, 0x10, 0x5b, 0x4a, 0x3e, 0x3d, 0x3f, 0x3f, 0x3d, 0x27, 0x15, 0x55, 0x59, 0x71, 0x49, 0x62,
	0x6e, 0x01, 0x44, 0x99, 0x52, 0x2d, 0x17, 0x67, 0x48, 0x66, 0x6e, 0x6a, 0x50, 0x62, 0x5e, 0x7a,
	0xaa, 0x90, 0x25, 0x17, 0x57, 0x71, 0x49, 0x62, 0x51, 0x49, 0x3c, 0x48, 0x95, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0xb7, 0x91, 0x94, 0x1e, 0xc4, 0x08, 0x3d, 0x98, 0x11, 0x7a, 0x21, 0x30, 0x23, 0x82,
	0x38, 0xc1, 0xaa, 0x41, 0x7c, 0x21, 0x53, 0x2e, 0x8e, 0xd4, 0xbc, 0x14, 0x88, 0x46, 0x26, 0x82,
	0x1a, 0xd9, 0x53, 0xf3, 0x52, 0x40, 0x3c, 0xa5, 0x52, 0x2e, 0xde, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4,
	0xe2, 0x12, 0x47, 0x88, 0x39, 0xea, 0x5c, 0xac, 0x45, 0x20, 0xb7, 0x40, 0x6d, 0xe7, 0xd7, 0x03,
	0x7b, 0x09, 0xee, 0x44, 0x0f, 0x86, 0x20, 0x88, 0xbc, 0x90, 0x01, 0x17, 0x0b, 0x71, 0x96, 0x79,
	0x30, 0x04, 0x81, 0x55, 0x3a, 0x71, 0x72, 0xb1, 0x27, 0x42, 0xbc, 0xe6, 0xa4, 0x10, 0x25, 0x87,
	0x3f, 0x24, 0x93, 0xd8, 0xc0, 0x5c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x2a, 0x32,
	0x9c, 0x72, 0x01, 0x00, 0x00,
}
